### ISSUE TITLE
support for algebraic mode 

### ISSUE THREAD

**Issue by dasoju** [kickingvegas/casual-calc#77]
Hi 
I use calc in algebraic mode by default, basically with below in my init file

add-hook 'calc-mode-hook #'calc-total-algebraic-mode)

With this is casual expected to work ?
how do i invoke casual-main-menu when I am in algebraic mode by default 

-K

**Comment by kickingvegas** [comment]
TBH, TIL that you could even have that mode. Will investigate.

**Comment by kickingvegas** [comment]
@dasoju Was able to figure out what was going on. Apparently Calc switches to a different keymap `calc-alg-map` when in total algebraic mode. I was able to configure Casual for `calc-total-algebraic-mode` with the following init sequence:

    (require 'calc)
    (require 'calc-mode)
    (require 'calc-ext)
    
    (add-hook 'calc-mode-hook #'calc-total-algebraic-mode)
    
    (define-key calc-alg-map (kbd "C-o") 'casual-main-menu)
    (define-key calc-mode-map (kbd "C-o") 'casual-main-menu)

I’d recommend defining the binding `C-o` for both keymaps `calc-alg-map` and `calc-mode-map` so that Casual is always available regardless of the input mode.

I’ll write up these findings in the [discussions](https://github.com/kickingvegas/Casual/discussions) group for others who use total algebraic mode.

Thanks for asking!

**Comment by dasoju** [comment]
Thanks for resolving the question Charles !
